"""Per-company horse designs.  Colours/motifs are only *inspired by* each brand's logo palette and
general style (loose geometric marks, never a copy of the logo).

spec = (company, horse_zh, horse_en, inspiration, coat)
coat keys: base, mane (str | list -> striped), legs, hoof, socks, blaze, star, shade,
           pattern (dapple|spots|roan|patch|stripes|hstripes|vstripes|quad|hsplit) + pcolor (str | list),
           marks: [("line",[pts],w) | ("ring",(cx,cy,r),w) | ("arc",(cx,cy,r),a0,a1,w)] drawn in mc,
           silks: (primary, secondary, pattern: solid|stripe|check|sash)
Body area is x 10..34, y 12..23.
"""
RAIN = ["#61bb46", "#fdb827", "#f5821f", "#e03a3e", "#963d97", "#009ddc"]
GOOG = ["#4285f4", "#ea4335", "#fbbc05", "#34a853"]

SPECS = {
    "AAPL": ("蘋果 Apple", "蘋果飛霜", "Apple Frost", "銀白機身配色＋復古彩虹鬃毛",
             dict(base="#e8eaee", mane=RAIN, hoof="#9aa0a6", silks=("#1d1d1f", "#ffffff", "stripe"))),
    "MSFT": ("微軟 Microsoft", "微軟四方", "Four Panes", "四色方塊分區毛色",
             dict(base="#f3f3f3", mane="#737373", pattern="quad", pcolor=["#f25022", "#7fba00", "#00a4ef", "#ffb900"],
                  silks=("#00a4ef", "#7fba00", "check"))),
    "NVDA": ("輝達 NVIDIA", "輝達閃電", "Green Bolt", "招牌螢光綠＋黑色眼睛同心圓",
             dict(base="#76b900", mane="#111111", legs="#2f5200", marks=[("ring", (25, 17, 4), 1), ("ring", (25, 17, 1.5), 1)], mc="#111111",
                  silks=("#111111", "#76b900", "stripe"))),
    "AMZN": ("亞馬遜 Amazon", "亞馬遜微笑", "Prime Smile", "深藍黑底＋橘色微笑弧線",
             dict(base="#232f3e", mane="#ff9900", hoof="#ff9900", marks=[("arc", (22, 11, 9), 20, 160, 2)], mc="#ff9900",
                  silks=("#ff9900", "#232f3e", "sash"))),
    "GOOGL": ("谷歌 Google", "谷歌彩點", "Four Dot Derby", "四原色點點花斑",
              dict(base="#ffffff", mane=GOOG, pattern="spots", pcolor=GOOG, silks=("#4285f4", "#fbbc05", "check"))),
    "META": ("Meta", "元宇宙無限", "Infinity Loop", "品牌藍＋雙環無限符號",
             dict(base="#0866ff", mane="#ffffff", marks=[("ring", (18, 17, 3.5), 1), ("ring", (26, 17, 3.5), 1)], mc="#dbe8ff",
                  silks=("#0866ff", "#ffffff", "stripe"))),
    "TSLA": ("特斯拉 Tesla", "特斯電光", "Red Lightning", "烈焰紅＋銀色閃電紋",
             dict(base="#e31937", mane="#d9d9d9", marks=[("line", [(21, 12), (18, 18), (23, 18), (20, 23)], 1)], mc="#eeeeee",
                  silks=("#e31937", "#222222", "solid"))),
    "AVGO": ("博通 Broadcom", "博通赤弧", "Crimson Arc", "白底＋紅色環形弧線",
             dict(base="#f1f1f1", mane="#cc092f", marks=[("arc", (22, 17, 5), 200, 340, 2)], mc="#cc092f",
                  silks=("#cc092f", "#ffffff", "sash"))),
    "NFLX": ("網飛 Netflix", "網飛紅幕", "Red Curtain", "黑底＋紅色絲帶鬃尾",
             dict(base="#141414", mane="#e50914", pattern="vstripes", pcolor="#3a0a0d", silks=("#e50914", "#141414", "stripe"))),
    "AMD": ("超微 AMD", "超微銳箭", "Sharp Arrow", "黑底＋紅色直角箭頭",
            dict(base="#161616", mane="#ed1c24", marks=[("line", [(18, 13), (28, 13), (28, 21)], 2)], mc="#ed1c24",
                 silks=("#ed1c24", "#161616", "check"))),
    "INTC": ("英特爾 Intel", "英特爾藍環", "Blue Ring", "經典藍＋環形標誌感",
             dict(base="#0068b5", mane="#ffffff", marks=[("arc", (22, 17, 5), 40, 320, 1)], mc="#ffffff",
                  silks=("#0068b5", "#ffffff", "stripe"))),
    "MU": ("美光 Micron", "美光記憶", "Memory Lane", "晶片藍＋條列式記憶體橫紋",
           dict(base="#1e5bbb", mane="#7ec8ff", pattern="hstripes", pcolor="#4f8fe0", silks=("#7ec8ff", "#1e5bbb", "stripe"))),
    "ORCL": ("甲骨文 Oracle", "甲骨神諭", "Red Oracle", "Oracle 紅＋深灰鬃毛",
             dict(base="#c74634", mane="#312d2a", star=True, silks=("#312d2a", "#c74634", "stripe"))),
    "CRM": ("賽富時 Salesforce", "雲端飛雲", "Cloud Nine", "天藍＋雲朵斑點",
            dict(base="#00a1e0", mane="#ffffff", pattern="dapple", pcolor="#7fd0f2", silks=("#00a1e0", "#ffffff", "check"))),
    "ADBE": ("奧多比 Adobe", "奧多比創意", "Creative Red", "全紅＋白色 A 形尖角",
             dict(base="#fa0f00", mane="#ffffff", marks=[("line", [(16, 22), (22, 13), (28, 22)], 2)], mc="#ffffff",
                  silks=("#fa0f00", "#ffffff", "sash"))),
    "QCOM": ("高通 Qualcomm", "高通電波", "Signal Boost", "高通藍＋深藍鬃毛",
             dict(base="#3253dc", mane="#1b2a6b", blaze=True, silks=("#1b2a6b", "#3253dc", "stripe"))),
    "COST": ("好市多 Costco", "好市多滿載", "Bulk Buy", "紅色底＋藍色橫條倉儲感",
             dict(base="#e31837", mane="#005daa", pattern="hstripes", pcolor="#005daa", silks=("#005daa", "#e31837", "stripe"))),
    "WMT": ("沃爾瑪 Walmart", "沃爾瑪星火", "Spark Saver", "藍底＋黃色火花鬃尾",
            dict(base="#0071ce", mane="#ffc220", star=True, socks=True, silks=("#ffc220", "#0071ce", "sash"))),
    "JPM": ("摩根大通 JPMorgan", "大通金融", "Blue Chip", "深藍＋銀灰鬃毛，穩重的藍籌",
            dict(base="#1b4f9c", mane="#e8e8e8", socks=True, silks=("#e8e8e8", "#1b4f9c", "stripe"))),
    "V": ("Visa", "維薩金帶", "Gold Band", "深藍＋金色鬃毛與馬蹄",
          dict(base="#1a1f71", mane="#f7b600", hoof="#f7b600", blaze=True, silks=("#1a1f71", "#f7b600", "stripe"))),
    "MA": ("萬事達 Mastercard", "萬事達雙環", "Twin Rings", "紅底＋重疊橘色雙圓",
           dict(base="#eb001b", mane="#f79e1b", marks=[("ring", (19, 17, 4.5), 1), ("ring", (26, 17, 4.5), 1)], mc="#f79e1b",
                silks=("#f79e1b", "#eb001b", "check"))),
    "UNH": ("聯合健康 UnitedHealth", "聯合安康", "Healing Hooves", "深藍＋橘色鬃毛",
            dict(base="#002677", mane="#ff612b", silks=("#ff612b", "#002677", "check"))),
    "LLY": ("禮來 Eli Lilly", "禮來紅駒", "Lilly Red", "禮來紅＋白色鬃毛",
            dict(base="#d52b1e", mane="#ffffff", blaze=True, silks=("#d52b1e", "#ffffff", "stripe"))),
    "XOM": ("埃克森美孚 ExxonMobil", "美孚烈油", "Crude Flame", "紅藍雙色：紅身藍鬃",
            dict(base="#e0112b", mane="#1a3b8f", legs="#8f0b1c", silks=("#1a3b8f", "#e0112b", "sash"))),
    "BRK-B": ("波克夏 Berkshire", "波克夏長青", "Oracle of Omaha", "深藍＋銀鬃，沉穩的價值馬",
              dict(base="#223a5e", mane="#cfd6e0", star=True, silks=("#cfd6e0", "#223a5e", "stripe"))),
    "PLTR": ("帕蘭泰爾 Palantir", "帕蘭神眼", "Seeing Stone", "純黑＋白襪白鬃，低調神祕",
             dict(base="#101010", mane="#ffffff", socks=True, silks=("#ffffff", "#101010", "check"))),
    "COIN": ("Coinbase", "幣基硬幣", "Coin Gallop", "鈷藍＋白色圓幣環",
             dict(base="#0052ff", mane="#ffffff", marks=[("ring", (22, 17, 5), 1)], mc="#ffffff",
                  silks=("#ffffff", "#0052ff", "stripe"))),
    "HOOD": ("羅賓漢 Robinhood", "羅賓綠羽", "Green Feather", "螢光綠＋羽毛斜紋",
             dict(base="#00c805", mane="#0b2f0b", pattern="stripes", pcolor="#009e04", silks=("#0b2f0b", "#00c805", "sash"))),
    "SMCI": ("美超微 Super Micro", "超微伺服", "Rack Runner", "黑底＋亮綠鬃毛",
             dict(base="#1b1b1b", mane="#7ac143", hoof="#7ac143", silks=("#7ac143", "#1b1b1b", "stripe"))),
    "DELL": ("戴爾 Dell", "戴爾藍圈", "Blue Orbit", "戴爾藍＋圓環",
             dict(base="#007db8", mane="#ffffff", marks=[("ring", (22, 17, 5), 1)], mc="#00496b",
                  silks=("#ffffff", "#007db8", "stripe"))),
    "APP": ("AppLovin", "應用閃躍", "App Sprint", "深藍＋青藍閃電",
            dict(base="#1b3b6f", mane="#4cc3ff", marks=[("line", [(20, 12), (24, 17), (20, 18), (25, 23)], 1)], mc="#4cc3ff",
                 silks=("#4cc3ff", "#1b3b6f", "check"))),
    "NOW": ("ServiceNow", "現在服務", "Service Now", "深墨綠＋螢光綠圓環",
            dict(base="#293e40", mane="#62d84e", marks=[("ring", (22, 17, 4), 1)], mc="#62d84e",
                 silks=("#62d84e", "#293e40", "stripe"))),
    "KO": ("可口可樂 Coca-Cola", "可樂狂奔", "Fizzy Dash", "可樂紅＋白色飄帶波紋",
           dict(base="#f40009", mane="#ffffff", marks=[("line", [(11, 18), (16, 20), (22, 17), (28, 20), (33, 17)], 1)], mc="#ffffff",
                silks=("#ffffff", "#f40009", "stripe"))),
    "PEP": ("百事 PepsiCo", "百事雙色", "Pepsi Wave", "上藍下紅＋白色波浪分界",
            dict(base="#ffffff", mane="#004b93", pattern="hsplit", pcolor=["#004b93", "#e32934"],
                 marks=[("line", [(11, 17), (16, 15), (22, 18), (28, 16), (33, 18)], 1)], mc="#ffffff",
                 silks=("#004b93", "#e32934", "sash"))),
    "DIS": ("迪士尼 Disney", "迪士尼夢駒", "Dream Castle", "夢幻藍＋白色星星",
            dict(base="#113ccf", mane="#ffffff", star=True, blaze=True, silks=("#ffffff", "#113ccf", "check"))),
    "NKE": ("耐吉 Nike", "耐吉勾勢", "Swoosh Runner", "黑底＋白色勾形弧線",
            dict(base="#111111", mane="#ffffff", marks=[("line", [(13, 15), (18, 20), (25, 19), (33, 13)], 2)], mc="#ffffff",
                 silks=("#ffffff", "#111111", "sash"))),
    "MCD": ("麥當勞 McDonald's", "麥當金拱", "Golden Arches", "紅底＋金黃雙拱門弧線",
            dict(base="#da291c", mane="#ffc72c", hoof="#ffc72c", marks=[("arc", (18, 20, 4.5), 180, 360, 2), ("arc", (27, 20, 4.5), 180, 360, 2)], mc="#ffc72c",
                 silks=("#ffc72c", "#da291c", "stripe"))),
    "SBUX": ("星巴克 Starbucks", "星巴克綠環", "Siren Green", "咖啡綠＋白色圓環",
             dict(base="#00704a", mane="#ffffff", marks=[("ring", (23, 17, 5), 1), ("ring", (23, 17, 2), 1)], mc="#ffffff",
                  silks=("#ffffff", "#00704a", "stripe"))),
    "BA": ("波音 Boeing", "波音藍天", "Blue Wings", "深藍＋淡藍鬃毛",
           dict(base="#0033a0", mane="#9cc3ff", blaze=True, silks=("#9cc3ff", "#0033a0", "sash"))),
    "CAT": ("開拓重工 Caterpillar", "開拓重蹄", "Heavy Hooves", "工程黃＋黑色四肢",
            dict(base="#ffcd11", mane="#111111", legs="#111111", hoof="#111111", silks=("#111111", "#ffcd11", "stripe"))),
    "HD": ("家得寶 Home Depot", "家得寶橘箱", "Orange Box", "橘色方塊感＋黑鬃",
           dict(base="#f96302", mane="#111111", socks=True, silks=("#111111", "#f96302", "check"))),
    "BAC": ("美國銀行 Bank of America", "美銀旗幟", "Flag Runner", "深藍＋紅色旗幟橫紋",
            dict(base="#012169", mane="#e31837", pattern="hstripes", pcolor="#e31837", silks=("#e31837", "#012169", "stripe"))),
    "WFC": ("富國銀行 Wells Fargo", "富國驛馬", "Stagecoach", "紅底＋黃色鬃毛（驛馬車配色）",
            dict(base="#d71e28", mane="#ffcd41", hoof="#ffcd41", silks=("#ffcd41", "#d71e28", "sash"))),
    "GS": ("高盛 Goldman Sachs", "高盛金蹄", "Gold Standard", "高盛藍＋銀白鬃",
           dict(base="#7399c6", mane="#f0f4fa", hoof="#d4af37", silks=("#f0f4fa", "#7399c6", "stripe"))),
    "T": ("AT&T", "電信環球", "Globe Trotter", "天藍＋白色地球經緯線",
          dict(base="#00a8e0", mane="#ffffff", marks=[("ring", (22, 17, 5), 1), ("line", [(17, 17), (27, 17)], 1)], mc="#ffffff",
               silks=("#ffffff", "#00a8e0", "stripe"))),
    "VZ": ("威瑞森 Verizon", "威瑞勾魂", "Red Check", "黑底＋紅色勾勾",
           dict(base="#161616", mane="#cd040b", marks=[("line", [(16, 17), (21, 22), (30, 13)], 2)], mc="#cd040b",
                silks=("#cd040b", "#161616", "stripe"))),
    "TMUS": ("T-Mobile", "洋紅電訊", "Magenta Mile", "洋紅粉＋白襪",
             dict(base="#e20074", mane="#ffffff", socks=True, blaze=True, silks=("#ffffff", "#e20074", "check"))),
    "CSCO": ("思科 Cisco", "思科長橋", "Bridge Runner", "科技藍＋白色直條橋樑紋",
             dict(base="#049fd9", mane="#ffffff", pattern="vstripes", pcolor="#bfeaf8", silks=("#ffffff", "#049fd9", "stripe"))),
    "IBM": ("國際商業機器 IBM", "藍色巨人", "Big Blue", "IBM 藍＋白色細橫條紋",
            dict(base="#1f70c1", mane="#ffffff", pattern="hstripes", pcolor="#cfe3f7", silks=("#ffffff", "#1f70c1", "stripe"))),
    "TXN": ("德州儀器 Texas Instruments", "德儀孤星", "Lone Star", "德州紅＋額頭孤星",
            dict(base="#c8102e", mane="#111111", star=True, blaze=True, silks=("#111111", "#c8102e", "stripe"))),
    "UBER": ("優步 Uber", "優步疾駛", "Night Rider", "純黑＋白襪白鬃",
             dict(base="#111111", mane="#ffffff", socks=True, silks=("#ffffff", "#111111", "stripe"))),
    "ABNB": ("愛彼迎 Airbnb", "愛彼迎珊瑚", "Coral Belo", "珊瑚粉紅＋白色小環",
             dict(base="#ff5a5f", mane="#ffffff", marks=[("ring", (22, 17, 3), 1)], mc="#ffffff",
                  silks=("#ffffff", "#ff5a5f", "sash"))),
    "PYPL": ("PayPal", "貝寶雙藍", "Twin Blue", "深藍＋亮藍上下雙色",
             dict(base="#003087", mane="#009cde", pattern="hsplit", pcolor=["#003087", "#009cde"],
                  silks=("#009cde", "#003087", "check"))),
    "SHOP": ("Shopify", "開店綠袋", "Green Bag", "萌芽綠＋額頭星",
             dict(base="#95bf47", mane="#5e8e3e", star=True, silks=("#5e8e3e", "#95bf47", "stripe"))),
    "PANW": ("派拓網路 Palo Alto", "派拓鐵衛", "Firewall", "橘紅斜紋＋黑鬃",
             dict(base="#fa582d", mane="#111111", pattern="stripes", pcolor="#c9421d", silks=("#111111", "#fa582d", "sash"))),
    "CRWD": ("群擎 CrowdStrike", "群擎獵鷹", "Falcon Strike", "黑底＋紅色獵鷹弧線",
             dict(base="#161616", mane="#ec0000", marks=[("line", [(13, 20), (22, 14), (32, 17)], 2)], mc="#ec0000",
                  silks=("#ec0000", "#161616", "stripe"))),
    "LULU": ("露露檸檬 Lululemon", "露露飛旋", "Lulu Loop", "紅底＋白色圓環",
             dict(base="#d31f3a", mane="#ffffff", marks=[("ring", (22, 17, 4.5), 1)], mc="#ffffff",
                  silks=("#ffffff", "#d31f3a", "stripe"))),
    "F": ("福特 Ford", "福特藍橢", "Blue Oval", "福特藍＋白色橢圓環",
          dict(base="#003478", mane="#ffffff", marks=[("ring", (22, 17, 5), 1)], mc="#ffffff",
               silks=("#ffffff", "#003478", "stripe"))),
    "SNDK": ("閃迪 SanDisk", "閃迪急電", "Flash Drive", "快閃紅＋黑色條紋",
             dict(base="#e60012", mane="#111111", pattern="hstripes", pcolor="#a8000d", silks=("#111111", "#e60012", "stripe"))),
    "STX": ("希捷 Seagate", "希捷綠旋", "Spin Doctor", "硬碟綠＋黑鬃斑紋",
            dict(base="#6cc24a", mane="#111111", pattern="dapple", pcolor="#8bd36d", silks=("#111111", "#6cc24a", "check"))),
}
